CREATE TABLE IF NOT EXISTS LOANS (
    ID INT,
    PRODUCT STRING,
    STATUS STRING,
    BALANCE INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO LOANS (ID, PRODUCT, STATUS, BALANCE) 
VALUES (1, 'Mortgage', 'DEFAULT', '500');