CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INT,
    TOY_NAME STRING,
    STATUS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CUSTOMER (ID, TOY_NAME, STATUS) 
VALUES (1, 'ZOMBIE ACTION FIGURE', 'IN STOCK');
