CREATE TABLE IF NOT EXISTS DEPOSITS (
    ID INT,
    PRODUCT STRING,
    STATUS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO DEPOSITS (ID, PRODUCT, STATUS) 
VALUES (1, 'YOUNG SAVER', 'OPEN');
