# name: Snowflake Deployment
# on:
#   push:
#     branches: [ main ]

# permissions:
#   id-token: write      # REQUIRED for OIDC
#   contents: read

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Snowflake CLI
#         uses: snowflakedb/snowflake-cli-action@v2.0
#         with:
#           cli-version: "3.11.0" # Minimum for OIDC
#           use-oidc: true         # Enables passwordless auth

#       - name: Deploy Code
#         env:
#           SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#           SNOWFLAKE_USER: github_service_user
#         run: snow sql -f ./scripts/setup.sql -x # Runs SQL


name: Snowflake Deploy
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml"

      - name: Run Deploy Script
        env:
          SNOWFLAKE_CONNECTIONS_MYCONN_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_MYCONN_USER: github_service_user
          SNOWFLAKE_CONNECTIONS_MYCONN_AUTHENTICATOR: SNOWFLAKE_JWT
        run: snow sql -f scripts/create_table.sql --connection myconn
