name: Snowflake Deploy
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          cli-version: "3.1.0"

      - name: Run Deploy Script
        env:
          # This maps your GitHub Secret to the Snowflake CLI
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: github_service_user
          SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
        run: snow sql -f scripts/create_table.sql
